export enum ConfiguracionSistemaKey {
  MARKETPLACE_COMMISSION = 'MARKETPLACE_COMMISSION',

  IVA_PERCENTAGE = 'IVA_PERCENTAGE',

  CURRENCY = 'CURRENCY',

  PAYMENT_TIMEOUT_MINUTES = 'PAYMENT_TIMEOUT_MINUTES',
  VOLUMETRIC_FACTOR = 'VOLUMETRIC_FACTOR',

  ADDITIONAL_VENDOR_SHIPPING_FACTOR = 'ADDITIONAL_VENDOR_SHIPPING_FACTOR',
}
